import 'package:weather/weather/repos/weather_repo.dart';

import '../../utils/dio_services.dart';
import '../../utils/errors.dart';
import '../models/model.dart';

class MockWeatherRepository implements WeatherRepository {
  final DioClient dioClient;

  MockWeatherRepository({required this.dioClient});

  @override
  Future<WeatherModel> getWeather(String city) async {
    await Future.delayed(
        const Duration(milliseconds: 500)); // Simulate network delay

    if (city.toLowerCase() != 'cairo') {
      throw WeatherFailure(message: 'City not found');
    }
    final mockData = {

      "location": {
        "name": "Cairo International Airport",
        "region": "Cairo",
        "country": "Egypt",
        "lat": 30.1219005584717,
        "lon": 31.4055995941162,
        "tz_id": "Africa/Cairo",
        "localtime_epoch": 1742061297,
        "localtime": "2025-03-15 19:54"
      },

      "current": {
        "last_updated_epoch": 1742060700,
        "last_updated": "2025-03-15 19:45",
        "temp_c": 26,
        "temp_f": 78.8,
        "is_day": 0,

        "condition": {
          "text": "Clear",
          "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
          "code": 1000
        },
        "wind_mph": 18.3,
        "wind_kph": 29.5,
        "wind_degree": 37,
        "wind_dir": "NE",
        "pressure_mb": 1017,
        "pressure_in": 30.03,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 32,
        "cloud": 0,
        "feelslike_c": 25.2,
        "feelslike_f": 77.3,
        "windchill_c": 24.9,
        "windchill_f": 76.8,
        "heatindex_c": 24.4,
        "heatindex_f": 76,
        "dewpoint_c": 4.9,
        "dewpoint_f": 40.8,
        "vis_km": 10,
        "vis_miles": 6,
        "uv": 0,
        "gust_mph": 27.7,
        "gust_kph": 44.6
      },

      "forecast": {

        "forecastday": [

          {
            "date": "2025-03-15",
            "date_epoch": 1741996800,

            "day": {
              "maxtemp_c": 32.3,
              "maxtemp_f": 90.2,
              "mintemp_c": 17.5,
              "mintemp_f": 63.6,
              "avgtemp_c": 23.9,
              "avgtemp_f": 75,
              "maxwind_mph": 18.6,
              "maxwind_kph": 29.9,
              "totalprecip_mm": 0,
              "totalprecip_in": 0,
              "totalsnow_cm": 0,
              "avgvis_km": 10,
              "avgvis_miles": 6,
              "avghumidity": 37,
              "daily_will_it_rain": 0,
              "daily_chance_of_rain": 0,
              "daily_will_it_snow": 0,
              "daily_chance_of_snow": 0,

              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "uv": 1.8
            },

            "astro": {
              "sunrise": "06:05 AM",
              "sunset": "06:03 PM",
              "moonrise": "07:13 PM",
              "moonset": "06:33 AM",
              "moon_phase": "Waning Gibbous",
              "moon_illumination": 100,
              "is_moon_up": 1,
              "is_sun_up": 0
            },

            "hour": [

              {
                "time_epoch": 1741989600,
                "time": "2025-03-15 00:00",
                "temp_c": 20.3,
                "temp_f": 68.5,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 10.7,
                "wind_kph": 17.3,
                "wind_degree": 34,
                "wind_dir": "NE",
                "pressure_mb": 1018,
                "pressure_in": 30.05,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 45,
                "cloud": 0,
                "feelslike_c": 20.3,
                "feelslike_f": 68.5,
                "windchill_c": 20.3,
                "windchill_f": 68.5,
                "heatindex_c": 20.3,
                "heatindex_f": 68.5,
                "dewpoint_c": 8.1,
                "dewpoint_f": 46.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 19.1,
                "gust_kph": 30.7,
                "uv": 0
              },

              {
                "time_epoch": 1741993200,
                "time": "2025-03-15 01:00",
                "temp_c": 19.7,
                "temp_f": 67.5,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 9.8,
                "wind_kph": 15.8,
                "wind_degree": 33,
                "wind_dir": "NNE",
                "pressure_mb": 1017,
                "pressure_in": 30.04,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 49,
                "cloud": 0,
                "feelslike_c": 19.7,
                "feelslike_f": 67.5,
                "windchill_c": 19.7,
                "windchill_f": 67.5,
                "heatindex_c": 19.7,
                "heatindex_f": 67.5,
                "dewpoint_c": 8.7,
                "dewpoint_f": 47.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 17.6,
                "gust_kph": 28.4,
                "uv": 0
              },

              {
                "time_epoch": 1741996800,
                "time": "2025-03-15 02:00",
                "temp_c": 19.1,
                "temp_f": 66.5,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 9.6,
                "wind_kph": 15.5,
                "wind_degree": 27,
                "wind_dir": "NNE",
                "pressure_mb": 1018,
                "pressure_in": 30.05,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 52,
                "cloud": 0,
                "feelslike_c": 19.1,
                "feelslike_f": 66.5,
                "windchill_c": 19.1,
                "windchill_f": 66.5,
                "heatindex_c": 19.1,
                "heatindex_f": 66.5,
                "dewpoint_c": 9.2,
                "dewpoint_f": 48.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 17.2,
                "gust_kph": 27.6,
                "uv": 0
              },

              {
                "time_epoch": 1742000400,
                "time": "2025-03-15 03:00",
                "temp_c": 18.6,
                "temp_f": 65.4,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 9.6,
                "wind_kph": 15.5,
                "wind_degree": 24,
                "wind_dir": "NNE",
                "pressure_mb": 1018,
                "pressure_in": 30.05,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 56,
                "cloud": 0,
                "feelslike_c": 18.6,
                "feelslike_f": 65.4,
                "windchill_c": 18.6,
                "windchill_f": 65.4,
                "heatindex_c": 18.6,
                "heatindex_f": 65.4,
                "dewpoint_c": 9.7,
                "dewpoint_f": 49.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 17.2,
                "gust_kph": 27.6,
                "uv": 0
              },

              {
                "time_epoch": 1742004000,
                "time": "2025-03-15 04:00",
                "temp_c": 18.1,
                "temp_f": 64.7,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 9.2,
                "wind_kph": 14.8,
                "wind_degree": 25,
                "wind_dir": "NNE",
                "pressure_mb": 1018,
                "pressure_in": 30.05,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 60,
                "cloud": 0,
                "feelslike_c": 18.1,
                "feelslike_f": 64.7,
                "windchill_c": 18.1,
                "windchill_f": 64.7,
                "heatindex_c": 18.1,
                "heatindex_f": 64.7,
                "dewpoint_c": 10.2,
                "dewpoint_f": 50.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 16.6,
                "gust_kph": 26.6,
                "uv": 0
              },

              {
                "time_epoch": 1742007600,
                "time": "2025-03-15 05:00",
                "temp_c": 17.8,
                "temp_f": 64.1,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 8.5,
                "wind_kph": 13.7,
                "wind_degree": 26,
                "wind_dir": "NNE",
                "pressure_mb": 1018,
                "pressure_in": 30.06,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 61,
                "cloud": 0,
                "feelslike_c": 17.8,
                "feelslike_f": 64.1,
                "windchill_c": 17.8,
                "windchill_f": 64.1,
                "heatindex_c": 17.8,
                "heatindex_f": 64.1,
                "dewpoint_c": 10.2,
                "dewpoint_f": 50.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 15.5,
                "gust_kph": 24.9,
                "uv": 0
              },

              {
                "time_epoch": 1742011200,
                "time": "2025-03-15 06:00",
                "temp_c": 17.5,
                "temp_f": 63.6,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 8.5,
                "wind_kph": 13.7,
                "wind_degree": 27,
                "wind_dir": "NNE",
                "pressure_mb": 1018,
                "pressure_in": 30.07,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 62,
                "cloud": 0,
                "feelslike_c": 17.5,
                "feelslike_f": 63.6,
                "windchill_c": 17.5,
                "windchill_f": 63.6,
                "heatindex_c": 17.5,
                "heatindex_f": 63.6,
                "dewpoint_c": 10.3,
                "dewpoint_f": 50.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 15.9,
                "gust_kph": 25.5,
                "uv": 0
              },

              {
                "time_epoch": 1742014800,
                "time": "2025-03-15 07:00",
                "temp_c": 18.1,
                "temp_f": 64.6,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 8.9,
                "wind_kph": 14.4,
                "wind_degree": 31,
                "wind_dir": "NNE",
                "pressure_mb": 1018,
                "pressure_in": 30.07,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 60,
                "cloud": 0,
                "feelslike_c": 18.1,
                "feelslike_f": 64.6,
                "windchill_c": 18.1,
                "windchill_f": 64.6,
                "heatindex_c": 18.1,
                "heatindex_f": 64.6,
                "dewpoint_c": 10.3,
                "dewpoint_f": 50.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 15.5,
                "gust_kph": 24.9,
                "uv": 0.4
              },

              {
                "time_epoch": 1742018400,
                "time": "2025-03-15 08:00",
                "temp_c": 20.7,
                "temp_f": 69.3,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 11.2,
                "wind_kph": 18,
                "wind_degree": 34,
                "wind_dir": "NE",
                "pressure_mb": 1019,
                "pressure_in": 30.08,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 50,
                "cloud": 0,
                "feelslike_c": 20.7,
                "feelslike_f": 69.3,
                "windchill_c": 20.7,
                "windchill_f": 69.3,
                "heatindex_c": 20.7,
                "heatindex_f": 69.3,
                "dewpoint_c": 10,
                "dewpoint_f": 50,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 14.3,
                "gust_kph": 23,
                "uv": 1.5
              },

              {
                "time_epoch": 1742022000,
                "time": "2025-03-15 09:00",
                "temp_c": 23.2,
                "temp_f": 73.8,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 12.8,
                "wind_kph": 20.5,
                "wind_degree": 28,
                "wind_dir": "NNE",
                "pressure_mb": 1019,
                "pressure_in": 30.09,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 38,
                "cloud": 0,
                "feelslike_c": 24.3,
                "feelslike_f": 75.8,
                "windchill_c": 23.2,
                "windchill_f": 73.8,
                "heatindex_c": 24.3,
                "heatindex_f": 75.8,
                "dewpoint_c": 8.3,
                "dewpoint_f": 46.9,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 14.7,
                "gust_kph": 23.6,
                "uv": 3.3
              },

              {
                "time_epoch": 1742025600,
                "time": "2025-03-15 10:00",
                "temp_c": 25.6,
                "temp_f": 78.1,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 13.4,
                "wind_kph": 21.6,
                "wind_degree": 26,
                "wind_dir": "NNE",
                "pressure_mb": 1019,
                "pressure_in": 30.1,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 29,
                "cloud": 0,
                "feelslike_c": 25,
                "feelslike_f": 77.1,
                "windchill_c": 25.6,
                "windchill_f": 78.2,
                "heatindex_c": 25,
                "heatindex_f": 77.1,
                "dewpoint_c": 6.3,
                "dewpoint_f": 43.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 15.4,
                "gust_kph": 24.8,
                "uv": 5.5
              },

              {
                "time_epoch": 1742029200,
                "time": "2025-03-15 11:00",
                "temp_c": 27.9,
                "temp_f": 82.2,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 13.4,
                "wind_kph": 21.6,
                "wind_degree": 27,
                "wind_dir": "NNE",
                "pressure_mb": 1019,
                "pressure_in": 30.08,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 22,
                "cloud": 0,
                "feelslike_c": 26.1,
                "feelslike_f": 79,
                "windchill_c": 27.9,
                "windchill_f": 82.2,
                "heatindex_c": 26.1,
                "heatindex_f": 79,
                "dewpoint_c": 4.2,
                "dewpoint_f": 39.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 15.4,
                "gust_kph": 24.8,
                "uv": 7.2
              },

              {
                "time_epoch": 1742032800,
                "time": "2025-03-15 12:00",
                "temp_c": 29.8,
                "temp_f": 85.7,
                "is_day": 1,
                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 13.4,
                "wind_kph": 21.6,
                "wind_degree": 30,
                "wind_dir": "NNE",
                "pressure_mb": 1018,
                "pressure_in": 30.06,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 17,
                "cloud": 0,
                "feelslike_c": 27.6,
                "feelslike_f": 81.8,
                "windchill_c": 29.9,
                "windchill_f": 85.7,
                "heatindex_c": 27.6,
                "heatindex_f": 81.8,
                "dewpoint_c": 2,
                "dewpoint_f": 35.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 15.4,
                "gust_kph": 24.8,
                "uv": 7.8
              },

              {
                "time_epoch": 1742036400,
                "time": "2025-03-15 13:00",
                "temp_c": 31.4,
                "temp_f": 88.5,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 14.3,
                "wind_kph": 23,
                "wind_degree": 36,
                "wind_dir": "NE",
                "pressure_mb": 1017,
                "pressure_in": 30.03,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 13,
                "cloud": 0,
                "feelslike_c": 29.2,
                "feelslike_f": 84.5,
                "windchill_c": 31.4,
                "windchill_f": 88.5,
                "heatindex_c": 29.2,
                "heatindex_f": 84.5,
                "dewpoint_c": 0,
                "dewpoint_f": 31.9,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 16.5,
                "gust_kph": 26.5,
                "uv": 7.1
              },

              {
                "time_epoch": 1742040000,
                "time": "2025-03-15 14:00",
                "temp_c": 32.2,
                "temp_f": 89.9,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 16.6,
                "wind_kph": 26.6,
                "wind_degree": 43,
                "wind_dir": "NE",
                "pressure_mb": 1016,
                "pressure_in": 30,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 12,
                "cloud": 0,
                "feelslike_c": 30,
                "feelslike_f": 86,
                "windchill_c": 32.2,
                "windchill_f": 89.9,
                "heatindex_c": 30,
                "heatindex_f": 86,
                "dewpoint_c": -1.1,
                "dewpoint_f": 30.1,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 19,
                "gust_kph": 30.6,
                "uv": 5.2
              },

              {
                "time_epoch": 1742043600,
                "time": "2025-03-15 15:00",
                "temp_c": 32.3,
                "temp_f": 90.2,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 17.4,
                "wind_kph": 28.1,
                "wind_degree": 43,
                "wind_dir": "NE",
                "pressure_mb": 1016,
                "pressure_in": 29.99,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 12,
                "cloud": 0,
                "feelslike_c": 30.1,
                "feelslike_f": 86.2,
                "windchill_c": 32.3,
                "windchill_f": 90.2,
                "heatindex_c": 30.1,
                "heatindex_f": 86.2,
                "dewpoint_c": -0.9,
                "dewpoint_f": 30.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 20.1,
                "gust_kph": 32.3,
                "uv": 3.1
              },

              {
                "time_epoch": 1742047200,
                "time": "2025-03-15 16:00",
                "temp_c": 31.5,
                "temp_f": 88.8,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 18.6,
                "wind_kph": 29.9,
                "wind_degree": 44,
                "wind_dir": "NE",
                "pressure_mb": 1016,
                "pressure_in": 29.99,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 13,
                "cloud": 0,
                "feelslike_c": 29.3,
                "feelslike_f": 84.7,
                "windchill_c": 31.5,
                "windchill_f": 88.8,
                "heatindex_c": 29.3,
                "heatindex_f": 84.7,
                "dewpoint_c": -0.2,
                "dewpoint_f": 31.7,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 21.4,
                "gust_kph": 34.4,
                "uv": 1.3
              },

              {
                "time_epoch": 1742050800,
                "time": "2025-03-15 17:00",
                "temp_c": 30.1,
                "temp_f": 86.2,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 18.3,
                "wind_kph": 29.5,
                "wind_degree": 40,
                "wind_dir": "NE",
                "pressure_mb": 1016,
                "pressure_in": 30.01,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 15,
                "cloud": 0,
                "feelslike_c": 27.9,
                "feelslike_f": 82.2,
                "windchill_c": 30.1,
                "windchill_f": 86.2,
                "heatindex_c": 27.9,
                "heatindex_f": 82.2,
                "dewpoint_c": 0.7,
                "dewpoint_f": 33.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 22.8,
                "gust_kph": 36.7,
                "uv": 0.3
              },

              {
                "time_epoch": 1742054400,
                "time": "2025-03-15 18:00",
                "temp_c": 27.4,
                "temp_f": 81.3,
                "is_day": 1,

                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "wind_mph": 17.9,
                "wind_kph": 28.8,
                "wind_degree": 37,
                "wind_dir": "NE",
                "pressure_mb": 1017,
                "pressure_in": 30.03,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 19,
                "cloud": 0,
                "feelslike_c": 25.5,
                "feelslike_f": 78,
                "windchill_c": 27.4,
                "windchill_f": 81.4,
                "heatindex_c": 25.5,
                "heatindex_f": 78,
                "dewpoint_c": 2,
                "dewpoint_f": 35.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 26.6,
                "gust_kph": 42.9,
                "uv": 0
              },

              {
                "time_epoch": 1742058000,
                "time": "2025-03-15 19:00",
                "temp_c": 26,
                "temp_f": 78.8,
                "is_day": 0,

                "condition": {
                  "text": "Clear",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 18.3,
                "wind_kph": 29.5,
                "wind_degree": 37,
                "wind_dir": "NE",
                "pressure_mb": 1017,
                "pressure_in": 30.03,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 32,
                "cloud": 0,
                "feelslike_c": 24.4,
                "feelslike_f": 76,
                "windchill_c": 24.9,
                "windchill_f": 76.8,
                "heatindex_c": 24.4,
                "heatindex_f": 76,
                "dewpoint_c": 4.9,
                "dewpoint_f": 40.8,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 27.7,
                "gust_kph": 44.6,
                "uv": 0
              },

              {
                "time_epoch": 1742061600,
                "time": "2025-03-15 20:00",
                "temp_c": 23.2,
                "temp_f": 73.7,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 17.7,
                "wind_kph": 28.4,
                "wind_degree": 38,
                "wind_dir": "NE",
                "pressure_mb": 1018,
                "pressure_in": 30.06,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 35,
                "cloud": 0,
                "feelslike_c": 24.1,
                "feelslike_f": 75.3,
                "windchill_c": 23.2,
                "windchill_f": 73.7,
                "heatindex_c": 24.1,
                "heatindex_f": 75.3,
                "dewpoint_c": 6.7,
                "dewpoint_f": 44.1,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 26.6,
                "gust_kph": 42.8,
                "uv": 0
              },

              {
                "time_epoch": 1742065200,
                "time": "2025-03-15 21:00",
                "temp_c": 21.9,
                "temp_f": 71.4,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 16.6,
                "wind_kph": 26.6,
                "wind_degree": 41,
                "wind_dir": "NE",
                "pressure_mb": 1018,
                "pressure_in": 30.06,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 41,
                "cloud": 0,
                "feelslike_c": 21.9,
                "feelslike_f": 71.4,
                "windchill_c": 21.9,
                "windchill_f": 71.4,
                "heatindex_c": 24,
                "heatindex_f": 75.2,
                "dewpoint_c": 7.9,
                "dewpoint_f": 46.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 26.1,
                "gust_kph": 42,
                "uv": 0
              },

              {
                "time_epoch": 1742068800,
                "time": "2025-03-15 22:00",
                "temp_c": 21,
                "temp_f": 69.8,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 14.5,
                "wind_kph": 23.4,
                "wind_degree": 39,
                "wind_dir": "NE",
                "pressure_mb": 1018,
                "pressure_in": 30.06,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 45,
                "cloud": 0,
                "feelslike_c": 21,
                "feelslike_f": 69.8,
                "windchill_c": 21,
                "windchill_f": 69.8,
                "heatindex_c": 24.1,
                "heatindex_f": 75.4,
                "dewpoint_c": 8.8,
                "dewpoint_f": 47.8,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 24,
                "gust_kph": 38.6,
                "uv": 0
              },

              {
                "time_epoch": 1742072400,
                "time": "2025-03-15 23:00",
                "temp_c": 20.4,
                "temp_f": 68.6,
                "is_day": 0,

                "condition": {
                  "text": "Clear ",
                  "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  "code": 1000
                },
                "wind_mph": 11.9,
                "wind_kph": 19.1,
                "wind_degree": 37,
                "wind_dir": "NE",
                "pressure_mb": 1018,
                "pressure_in": 30.06,
                "precip_mm": 0,
                "precip_in": 0,
                "snow_cm": 0,
                "humidity": 50,
                "cloud": 0,
                "feelslike_c": 20.4,
                "feelslike_f": 68.6,
                "windchill_c": 20.4,
                "windchill_f": 68.6,
                "heatindex_c": 20.4,
                "heatindex_f": 68.6,
                "dewpoint_c": 9.6,
                "dewpoint_f": 49.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10,
                "vis_miles": 6,
                "gust_mph": 20.1,
                "gust_kph": 32.4,
                "uv": 0
              }
            ]
          }
        ]
      }
    };

    return WeatherModel.fromJson(mockData);
  }
}
